import React from 'react'
import './CloudStyles.css'


const Cloud = () => {
    return (
        <div className='cloud'>
            <div className="container">
                <div className="content">
                    <h2><span>Todas las versiones </span>de Windows </h2>
                    <p>A continuacion pasare a explicar de manera sencilla todos los sistemas operativos que tuvo Windows.</p>
                    <h2>Windows 1.0</h2>
                    <p>Aunque ya se hablaba de la existencia de la primera versión del sistema operativo antes de la presentación de Windows 1.0, lo cierto es que hasta el 20 de noviembre del año 1985 no se anunció de manera oficial esta primera versión del sistema. Una versión que ofrecía poca funcionalidad y que no se trataba de un sistema operativo completo, ya que más bien era una extensión gráfica de MS-DOS que hacía pensar en dejar atrás el uso de comandos.</p>
                    <p>Desarrollado 16 bits requería de 320 KBs de memoria RAM, una tarjeta gráfica y una unidad de disquete para funcionar, el precio de venta era de 99$. La versión 1.0 tuvo soporte hasta el 31 de diciembre de 2001, por lo que, a pesar de ser una versión sin apenas funcionalidad, los de Redmond estuvieron ofrecieron soporte durante poco más de 16 años hasta que quedó obsoleto.</p> 
                    <p>No es de los más populares, pero con él inicia la historia de un sistema operativo que ha conseguido hacerse todo un éxito con el paso de los años. Aquí empieza el recorrido de un sistema operativo con éxito que no ha sabido enamorar desde sus principios.</p>
                    <h2>Windows 2.0</h2>
                    <p>Mientras tanto, justo dos años más tarde, en noviembre de 1987, llegaba Windows 2.0. Una versión que fue actualizada rápidamente con la v2.03 y que ya incluía por primera vez ventanas que podían solaparse entre ellas. Eso por no hablar de que ya incluía ciertas utilidades que, podríamos decir, iban a ser el origen de las actuales herramientas de ofimática. Esta versión de fue la primera en contener el procesador de textos Microsoft Word y la hoja de cálculo Microsoft Excel por primera vez, ello provocó que esta versión de el sistema operativo tuviera mucho mejor acogida en el mercado. Sin embargo, pronto vieron que tenían que mejorarlo por su baja comercialización.</p>
                    <p>Fue mucho más popular que la anterior y ahí ya empezaba a nombrarse mucho más este sistema operativo. Con él encontramos el primer panel de control. Tuvo soporte hasta la misma fecha que la versión anterior. Es decir, hasta el 31 de diciembre de 2001, momento en el que Microsoft decidió descontinuar las versiones 1.0 y 2.0. Además, aquí debemos mencionar también Windows 2.1, creada en mayo de 1988 y que se encuentra actualmente descontinuada. Es una versión ligeramente modificada con algunas mejoras en sus aplicaciones, en donde está MS Paint.</p> 
                    <h3>Windows 3.0</h3>
                    <p>El 22 de mayo de 1990, se libera y se lanza el sistema operativo Windows 3.0 que llega con una interfaz gráfica en la que ya se comenzaban a apreciar nuevos elementos visuales además de las exitosas «ventanas». Fue la primera versión que tuvo éxito a nivel comercial pudiendo competir con Apple Macintosh y Commodore Amiga en el mercado. Se llegaron a vender hasta dos millones de copias en tan solo unos meses desde su lanzamiento. Aunque en este momento todavía se utilizaba mayormente MS-DOS para ejecutar programas y juegos en los ordenadores personales.</p> 
                    <p>Con la actualización al 3.1 en abril de 1992, el sistema recibió el famoso juego del Buscaminas que tanto entretenimiento ha ofrecido a lo largo de los años, entre otros juegos que tendremos en nuestra memoria. Además, hay que destacar también la existencia del administrador de archivos y de la compatibilidad con las tipografías TrueType desarrolladas anteriormente por Apple. Una versión a la que la compañía ofreció soporte hasta el 31 de diciembre de 2001. Misma fecha que las dos anteriores. Se instalaba con disquetes de 3 ½.</p> 
                    <h2>Windows 95</h2>
                    <p>El 24 de agosto de 1995 es una fecha importante en la vida del sistema operativo de Microsoft, ya que es el día en el que fue lanzada la famosa versión Windows 95. La primera versión que ofrece una interfaz muy mejorada y donde ya aparecen la barra de tareas y el menú Inicio, dos elementos muy importantes y característicos de Microsoft que siguen siendo parte hoy en día del sistema operativo. Eso sin olvidar que incluía Internet Explorer, el navegador web que tantos años ha estado acompañando al sistema y por lo tanto, el soporte para navegar por Internet.</p> 
                    <p>Una versión destinada al mercado de consumo y con la que se pasaba de una arquitectura multitarea cooperativa de 16 bits a una arquitectura apropiativa de 32 bits. Fue también la primera edición de este sistema operativo que soportaba el modo multitarea. Vendieron más de 7 millones de copias en su primera semana y el éxito fue impresionante. Es verdad que invirtieron mucho en publicidad y en darse a conocer. Hay que tener en cuenta que, el fin del soporte estándar para esta versión, fue el 31 de diciembre del año 2000, pero tuvo un soporte extendido que duró un año más, es decir, hasta el 31 de diciembre de 2001.</p>
                    <h2>Windows NT Server</h2>
                    <p>Este es un sistema operativo para servidores cuya primera versión fue publicada en julio de 1993, que destaca por ser ampliable e independiente de la plataforma y hardware. Se podía ejecutar en sistemas basados en procesadores Intel x86, RISC y DEC Alpha para que sus usuarios pudieran elegir sus sistemas informáticos. Destacada por estar enfocado a estaciones de trabajo y servidor de red.</p>
                    <p>Necesitaba un 386 con unos recursos mínimos de 75 MB de disco duro libre y 12 MB de RAM. Su primera versión fue NT 3.1, después hubo una versión mucho más mejorada NT 3.5 y otra llamada NT 4.</p>
                    <p>Esta versión específica tuvo gran acogida debido a la interfaz gráfica, casi idéntica a la del 95. La versión NT 4.0 Server fue diseñada para gestión de redes, con una versión especial para empresas (NT 4.0 Server, Enterprise Edition). La edición NT 4.0 Terminal Server era la primera en ofrecer acceso remoto al Escritorio. La edición Windows NT 4.0 Workstation tenía todo el soporte para Office, Internet Explorer y reproductores multimedia estando enfocada al uso empresarial. Finalmente, Microsoft desarrolló otra versión específica para empresas, Windows NT 4.0 Embedded, destinada a funcionar en cajeros automáticos, máquinas expendedoras y máquinas arcade (recreativas).</p>
                    <h2>Windows 98</h2>
                    <p>Aunque antes de la llegada de Windows 98 se sucedieron las distintas versiones del 95 mencionadas anteriormente con el nombre comercial NT, enfocadas especialmente al entorno empresarial e industrial, tres años después se lanzó una nueva edición. El 25 de junio de 1998, Microsoft lanzaba la nueva versión de su sistema operativo: Windows 98. Al igual que la anterior, adquirió como nombre las dos últimas cifras del año de su lanzamiento y era una versión que llegaba con el sistema de archivos FAT32 que trató de potenciar el acceso a la red. Además, incluyó la compatibilidad con lectores de DVDs y la incorporación de los primeros puertos USB.</p>
                    <p>Sin embargo, una mayor complejidad en el sistema hizo que se penalizara de gran manera el rendimiento del sistema, por lo que se convirtió en una de las versiones de Windows más criticadas por su lentitud y falta de fiabilidad en comparación con su antecesor del 95, que en este sentido había dejado el listón muy alto.</p>
                    <p>En mayo de 1999 se lanzó la versión 2.0 de este sistema operativo bajo el nombre de Windows 98 Segunda Edición (SE) que traía novedades como Internet Explorer 5, conexión compartida y Microsoft Netmeeting 3.0. Aun así, fue una versión que tuvo soporte estándar hasta el 30 de junio de 2002 y un soporte extendido que finalizó el 11 de julio de 2006.</p>
                    <h2>Windows 2000</h2>
                    <p>El 29 de marzo de 1999 se lanza el sistema operativo NT 5.0 EUR Edition, que no era otra cosa que la versión alemana de Windows NET 5.0 y que pasaría a llamarse Windows 2000 posteriormente. Una versión del sistema que Microsoft desarrolló como parte de su línea profesional. El objetivo era ofrecer todo el rendimiento a aquellos usuarios avanzados y profesionales que ejecutaban programas de alto rendimiento. De esta versión se filtró parte de su código fuente en Internet. Esto hizo que la compañía decidiese utilizar su núcleo para desarrollar la nueva versión del sistema.</p>
                    <p>Además de continuar el camino de NET, enfocándose a los negocios, incluyó nuevas opciones para una mayor protección de archivos. Se desarrollaron diferentes versiones más específicas encaminadas a usos muy concretos: Windows 2000 Professional, Server, Advanced Server, Datacenter Server y Advanced Server Limited Edition.  El soporte estándar de esta versión finalizó el 30 de junio de 2005, mientras que el soporte extendido acabó el 13 de julio de 2010.</p>
                    <p>Datacenter Server se lanzó meses después de las ediciones iniciales. Además, Microsoft vendió Windows Advanced Server 2000 Limited Edition y Windows Datacenter Server 2000 Limited Edition, que se ejecutaban en microprocesadores Intel Itanium de 64 bits. Aunque cada edición de este sistema operativo estaba dirigida a un mercado diferente, compartían un conjunto básico de características que incluyen muchas utilidades del sistema, como Microsoft Management Console y aplicaciones estándar de administración de sistemas.</p>
                    <p>Microsoft comercializó Windows 2000 como la versión de este sistema operativo más segura hasta el momento. Sin embargo, se convirtió en el objetivo de una serie de ataques de virus de alto perfil, como Code Red y Nimda.</p>
                    <h2>Windows Me</h2>
                    <p>Windows Millenium es una versión del sistema operativo de Microsoft lanzando el 14 de septiembre del año 2000 en formato gráfico híbrido de 16/32 bits. Fue diseñado por Microsoft para los usuarios de PC. Después de la madurez alcanzada por otras versiones anteriores como Windows 95 y Windows 98 no tuvo la aceptación por los usuarios que esperaba la compañía debido a los continuos errores que arrojaba (los famosos pantallazos azules) y las desventajas de su uso.</p>
                    <p>Estaba dirigido específicamente a usuarios de ordenadores domésticos. Incluía Internet Explorer 5.5, Media Player 7 y, como novedad, el software Movie Maker, que proporcionaba edición de video básica. Microsoft también actualizó la interfaz gráfica de usuario, las funciones de shell y el Explorador.</p>
                    <p>Cabe destacar que no está construido bajo el núcleo de Windows NT ya que solo se usó en los sistemas operativos profesionales hasta ese momento, aunque sí lo haría después su sustituto Windows XP. Tanto es así, que muchos usuarios que probaron Me en sus equipos volvieron a versiones anteriores de Windows 98 al poco tiempo y esperando que desde Redmond se tomaran cartas en el asunto. El soporte estándar finalizó a finales de 2003, poco más de tres años, mientras que el soporte extensión llegó hasta mediados del año 2006, concretamente hasta el mes de julio de ese año.</p>
                    <p>A partir de septiembre de 2011, los servidores de Windows Update v4 se apagaron, lo que afectó a todas las versiones de la familia causando que los intentos de actualización se atasquen en un bucle sin fin. El catálogo de actualizaciones de Microsoft solo conserva las actualizaciones heredadas para Windows 2000.</p>
                    <h2>Windows XP</h2>
                    <p>Otro gran salto en el desarrollo y evolución del sistema operativo de Microsoft se produjo el 25 de octubre del año 2001, momento en el que se lanzaba este nuevo sistema operativo. La primera versión del siglo XXI y que supuso un gran éxito al ser un producto de gran calidad. Una versión que fue construida a partir del kernel de Windows NT y que llegó en dos ediciones distintas, Home y Professional.</p>
                    <p>En el aspecto visual, hay que destacar grandes mejoras en la interfaz de usuario, con nuevos iconos, menús y opciones que permitían a los usuarios profundizar y controlar mucho más todo tipo de tareas sobre el sistema. Pero no sólo se quedó en ofrecer mejoras gráficas, sino que también llegó con un gran incremento de velocidad y agilidad.</p>
                    <p>Esta versión incorporó funciones como el cifrado de archivos del sistema, soporte para redes WiFi, la asistencia remota y su versión de 64 bits, lo cual provocó una explosión en el mercado de los sistemas operativos. Esta versión tuvo una gran aceptación siendo la edición mayoritaria en los hogares hasta 2012. Tuvo soporte estándar por parte de Microsoft hasta el 14 de abril de 2009, mientras que el soporte extendido duró hasta el 8 de abril de 2014.</p>
                    <p>No podemos decir adiós a Windows XP sin hablar de Windows XP Tablet Ed. Versión del popular y colorido sistema operativo que se diseñó y adaptó para que funcionase en las pesadas losas que eran las tablets de aquella época. Era prácticamente igual que su hermano mayor, sólo que además disponía de soporte para lápiz y otras funciones táctiles, además de incorporar una serie de aplicaciones exclusivas de las tablets. Realmente fue un sistema que incorporó muchas novedades y mejores que a día de hoy se siguen usando, y de las que se han nutrido otros. Pero lo cierto es que se vendieron tan pocas tablets en aquellos tiempo, que el sistema lo usó muy poca gente, y cayó en el olvido.</p>
                    <h2>Windows Vista</h2>
                    <p>Hubo que esperar hasta 6 años para la llegada de la nueva versión del sistema. Una versión que Microsoft lanzó mundialmente el 30 de enero de 2007, llegaba con infinidad de nuevas características y funciones. Un Shell rediseñado y una interfaz con grandes cambios y enfocada en mejorar la seguridad de los usuarios que, por el contrario, no fue del agrado de la gran mayoría de ellos.</p>
                    <p>Con esta actualización pudimos ver la interfaz Aero UI que, sin duda, ofrecía un gran atractivo a nivel visual, pero que resultó ser demasiado problemático en equipos menos potentes. Un cúmulo de circunstancias que hizo que se convirtiera en uno de los fiascos de la historia del sistema operativo a pesar de que se tenían grandes expectativas en la empresa.</p>
                    <p>Era la primera versión de Microsoft que se dirigía a equipos personales y de oficina, portátiles y tablets. Pero los continuos problemas, la lentitud y sobrecargas, hicieron sombra a todas las novedades gráficas. Esta versión recibió soporte estándar por parte de la compañía hasta el 10 de abril de 2012, mientras que el soporte extendido se alargó hasta el 11 de abril de 2017.</p>
                    <h2>Windows 7</h2>
                    <p>El 22 de octubre de 2009, Microsoft anunció el lanzamiento de su nueva versión como solución al fiasco de Windows Vista y que resultó una de las versiones más importantes del sistema operativo de Microsoft desde el anterior Windows XP. Algo que ha quedado retratado en la historia del sistema operativo, ya que ha sido etiquetada como una de las versiones más sólidas. Fue creado para utilizar en los diferentes ordenadores, incluyendo portátiles, tablets, netbooks y más.</p>
                    <p>Añadía soporte multi touch, un Windows Shell rediseñado, nueva barra de tareas, sistema de red, mejoras en el rendimiento y su velocidad y una reducción del consumo de recursos. Además, introdujo el nuevo diseño de la barra de tareas, dejándola más ancha, y un sistema con iconos de mayor tamaño. El soporte estándar de esta actualización duró hasta el 13 de enero de 2015, mientras que el soporte extendido llegó hasta el 14 de enero de 2020, por lo que, aunque puede haber usuarios que aún lo tengan no es lo más probable.</p>
                    <h2>Windows 8</h2>
                    <p>Prácticamente tres años después, el 26 de octubre de 2012, se lanzó esta nueva versión. Una versión que añadía soporte para microprocesadores ARM y cuya interfaz llegaba modificada para hacerla más adecuada para su uso con pantallas táctiles, mostrando nuevos efectos planos para ventanas y botones con un color simple.</p>
                    <p>Esto supuso también la eliminación del clásico menú de Inicio por Tiles, algo que no fue del agrado de la gran mayoría de usuarios. Por primera vez desde Windows 95 el sistema operativo prescindía de uno de los elementos más importantes como es el botón de Inicio de Windows.</p>
                    <p>La escasa aceptación de la interfaz Metro por parte de los usuarios hizo que Microsoft lanzase Windows 8.1 para intentar dar respuesta a los usuarios que echaban de menos algunos elementos tradicionales del sistema y que recuperaba algunas de las características. El soporte estándar y extendido de esta versión 8 finalizó el 12 de enero de 2016, mientras que en el caso de Windows 8.1, el soporte estándar duró hasta el 9 de enero de 2018 y el extendido aún está vigente hasta el 10 de enero de 2023. Todavía puede quedar algún usuario que esté utilizando este sistema operativo, aunque varios se han lanzado al cambio de Windows 10.</p>
                    <h2>Windows 10</h2>
                    <p>Windows 10 es una de las mas recientes versiónes del sistema operativo de Microsoft, lanzada en 2015. Destaca por su interfaz de usuario moderna y familiar, que incluye el menú de Inicio y los Live Tiles. El menú de Inicio combina el diseño clásico de Windows 7 con las baldosas en vivo introducidas en Windows 8. Las baldosas en vivo proporcionan información actualizada en tiempo real sobre aplicaciones y noticias.</p>
                    <p>Una característica importante de Windows 10 es Continuum, que permite una transición fluida entre el modo de escritorio tradicional y el modo de pantalla táctil optimizado. Si utilizas un dispositivo híbrido como una tableta con teclado desmontable, Windows 10 cambiará automáticamente entre los modos según cómo estés utilizando el dispositivo.</p>
                    <p>Microsoft Edge es el navegador web predeterminado de Windows 10. Reemplaza a Internet Explorer y ofrece una experiencia de navegación más rápida y segura. Con características como la toma de notas en páginas web, la vista de lectura sin distracciones y la integración con Cortana, Edge proporciona una experiencia moderna y mejorada para los usuarios.</p>
                    <p>Windows 10 introduce el concepto de aplicaciones universales, diseñadas para funcionar en diferentes dispositivos con Windows 10, como PC, tabletas, teléfonos y Xbox. Estas aplicaciones se pueden descargar desde la tienda Windows Store y ofrecen una experiencia coherente en todos los dispositivos.</p>
                    <h2>Windows 11</h2>
                    <p>Windows 11 es la última versión del sistema operativo de Microsoft, lanzada en octubre de 2021. Esta nueva versión presenta una serie de características destacadas que mejoran la experiencia de los usuarios.</p>
                    <p>Una de las principales novedades de Windows 11 es su interfaz de usuario rediseñada. Se ha introducido un nuevo menú de Inicio centrado, iconos rediseñados, esquinas redondeadas y una barra de tareas en el centro de la pantalla. Estos cambios brindan un aspecto más moderno y estéticamente agradable, al tiempo que mejoran la productividad al tener las aplicaciones y ventanas principales al alcance de la mano.</p>
                    <p>La multitarea también ha sido mejorada en Windows 11. Se han incorporado nuevas funciones, como "Snap Layouts", que permite organizar y redimensionar fácilmente las ventanas abiertas en diferentes diseños. Además, se ha añadido "Snap Groups" para restaurar grupos de aplicaciones abiertas y "Snap Assist" para facilitar la búsqueda y apertura rápida de aplicaciones.</p>
                </div>
            </div>
        </div>
    )
}

export default Cloud
